### ISSUE TITLE
Peer-to-Peer-Review-02-12-2022

### ISSUE THREAD

**Issue by tanveerisonline** [quavo19/Awsome-books#3]
### Hi Team @quavo19,  @Outkarm,  
            **Hi guys you have done everything in the correct order except the following thing please make the following changes to your project.**

- [x] Kindly try to fix your Single Page Application (SPA) error as your website is showing all data on one page but not as preferred.
- [x] Kindly fix your js code as it's not working while clicking on Add Button no data is being added.
- [x] Kindly update your readme as your live demo link is not working.
- [x] Kindly fix the date and time on your website as it's not being shown on your website.

Happy Coding 😉 😉 😉.

**Comment by Lucas-Erkana** [comment]
Hi @quavo19 && @Outkarm 

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media3.giphy.com/media/hXz6GN0ZilLwhgLo49/giphy.gif"/>

## Highlights
- All linters passed ✔️ 
- Form works as required ✅ 

## Required Changes ♻️
-Kindly try to stick to the design
**Your Design**
![image](https://user-images.githubusercontent.com/41428579/205249487-3c01fee8-3c81-48ff-a35f-40a3cb77970a.png)

**Required Design:**
![image](https://user-images.githubusercontent.com/41428579/205249794-6bf3a7db-2c5d-410c-b52f-85052c7774ab.png)







## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by quavo19** [comment]
Hi @Lucash2022 and @tanveerisonline,
thank you both for requesting improvements, my teammate and I have been working on your suggestions and I'm proud to say **WE DID IT** 🥳 😃 everything works as it should.

**Comment by quavo19** [comment]
**hello @Lucash2022  &  @tanveerisonline** 
Thank you both for requesting improvements on my project
as we know, Change is good, and it got my teammate and i working even harder to resolve any errors.
and I'm proud to say  **all issues have been resolved** 😃

**Comment by Lucas-Erkana** [comment]
At this [line ](https://github.com/quavo19/Awsome-books/blob/e3808b0faec189601917ccc7f80fa534523aea92/index.html#L62)
Kindly change the information to the Companies requirement. If a company asks you design a contact form then it should contain the companies details
Your desing is :
![image](https://user-images.githubusercontent.com/41428579/205282824-d7d19b95-e4bc-464c-b522-0a454df449e6.png)

Correct Requirement:
![image](https://user-images.githubusercontent.com/41428579/205283257-dd75b933-3596-4f8c-a22e-d4898bfa95fe.png)

Kindly add the current date as per requirement, here's how it can be [done](https://www.w3schools.com/js/js_date_methods.asp#:~:text=The%20new%20Date()%20Constructor,the%20current%20date%20and%20time.):
Your Image:
<img width="292" alt="image" src="https://user-images.githubusercontent.com/41428579/205283468-61621679-c014-424e-88d3-3c55b1070e6b.png">
Required Design:
<img width="150" alt="image" src="https://user-images.githubusercontent.com/41428579/205283705-f08a3b42-1064-4453-b539-fed217d2df30.png">

**Comment by quavo19** [comment]
hello, @Lucash2022 nice checking up 😄 
as it is good to make the work perfect, a medium-fidelity wireframe is not like a design template, content can be changed. and that is why I choose my own details
